config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  resources :tests do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    post :start, on: :member
  end

  resources :results, only: %i[show update] do
    get :result, on: :member
  end

  get :signup, to: 'users#new'
  resources :users, only: :create

  get :login, to: 'sessions#new'
  resources :sessions, only: :create

  get '/logout', to: 'sessions#destroy'

  get '/register', to: 'users#new', as: 'register'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_test, only: [:new, :create]
  before_action :find_question, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :question_not_found

  def show
    @test = @question.test
  end

  def edit
    @test = @question.test
  end

  def new
    @question = @test.questions.build
  end

  def create
    @question = @test.questions.build(question_params)
    if @question.save
      redirect_to question_path(@question), notice: 'Вопрос успешно создан'
    else
      render 'new'
    end
  end

  def update
    if @question.update(question_params)
      redirect_to question_path(@question), notice: 'Вопрос успешно обовлён'
    else
      render 'edit'
    end
  end

  def destroy
    @test = @question.test
    @question.destroy
    redirect_to test_path(@test), notice: 'Вопрос успешно удален'
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_not_found
    render plain: 'Вопрос не найден', status: :not_found
  end

  def question_params
    params.require(:question).permit(:body)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for [@question.new_record? ? @test : nil, @question] do |f| %>

<%= render 'shared/errors', resource: @question %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

<%= link_to 'Назад к тесту', test_path(@test) %>

app/views/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td>
    <%= link_to 'Просмотр', question_path(question) %>
    <%= link_to 'Редактировать', edit_question_path(question) %>
    <%= button_to 'Удалить', question_path(question), method: :delete, data: { confirm: 'Вы уверены?' } %>
</tr>

app/views/questions/edit.html.erb
<h1>Изменение вопроса</h1>

<%= render 'form' %>

app/views/questions/new.html.erb
<h1>Создание нового вопроса</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<h1>Просмотр вопроса</h1>

<p><strong>Текст вопроса:</strong> <%= @question.body %></p>

<%= link_to 'Редактировать', edit_question_path(@question) %> |
<%= link_to 'Назад к тесту', test_path(@test) %> |
<%= button_to 'Удалить', question_path(@question), method: :delete, data: { confirm: 'Вы уверены?' } %>

<h2>Answers</h2>

<ol>
  <%= render @question.answers %>
</ol>

<%= link_to 'Новый ответ', new_question_answer_path(@question) %>