config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  resources :tests do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    post :start, on: :member
  end

  resources :results, only: %i[show update] do
    get :result, on: :member
  end

  get :signup, to: 'users#new'
  resources :users, only: :create

  get :login, to: 'sessions#new'
  resources :sessions, only: :create

  get '/logout', to: 'sessions#destroy'

  get '/register', to: 'users#new', as: 'register'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  SUCCESS_RATIO = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_current_question

  def successful?
    success_rate >= SUCCESS_RATIO
  end

  def success_rate
    correct_questions.to_f / test.questions.count * 100
  end

  def current_question_number
    test.questions.index(current_question) + 1
  end
  
  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  private

  def set_current_question
    self.current_question = next_question
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = next_question unless completed?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if new_record?
      test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :update, :result]

  def show
  end

  def result
  end

  def update
    @result.accept!(params[:answer_ids])

    if @result.completed?
      redirect_to result_result_path(@result)
    else
      render :show
    end
  end

  private

  def set_result
    @result = Result.find(params[:id])
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/result.html.erb
<h1>Тест <%= @result.test.title %> завершен!</h1>

<% if @result.successful? %>
  <p style="color: green;">Поздравляем! Вы успешно прошли тест. Ваш процент успеха составляет <%= @result.success_rate %>%.</p>
<% else %>
  <p style="color: red;">К сожалению, вы не прошли тест. Ваш процент успеха составляет <%= @result.success_rate %>%.</p>
<% end %>

<p><%= link_to 'Вернуться к списку тестов', tests_path %></p>

app/views/results/show.html.erb
<h1>Passing the <%= @result.test.title %> Test</h1>

<b>
  Question <%= @result.current_question_number %> out of <%= @result.test.questions.count %>: <%= @result.current_question.body %> 
</b>

<%= form_with url: result_path(@result), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @result.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>  
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= form.submit 'Next' %></p>
<% end %>