config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  resources :tests do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    post :start, on: :member
  end

  resources :results, only: %i[show update] do
    get :result, on: :member
  end

  get :signup, to: 'users#new'
  resources :users, only: :create

  get :login, to: 'sessions#new'
  resources :sessions, only: :create

  get '/logout', to: 'sessions#destroy'

  get '/register', to: 'users#new', as: 'register'
end

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; <%= current_year %> <%= author_name %></p>
  <p><%=  github_url("bursachelio", "test-guru") %></p>
  <p>Учебный проект в онлайн-школе <%= link_to "Thinknetica", "https://thinknetica.com", target: "_blank" %></p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <% if logged_in? %>
      <p class="nav user">Welcome, <b><%= current_user.email %></b> Guru</p>
      <%= link_to 'Logout', logout_path %>
    <% else %>
      <%= link_to 'Register', register_path %>
      <%= link_to 'Login', login_path %>
    <% end %>
    <%= link_to 'Project Name', root_path %>
    
    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>